
#!/bin/bash

# Định nghĩa các biến môi trường
PROD_URL="https://eknujhmrispkgzhrywfv.supabase.co"
PROD_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbnVqaG1yaXNwa2d6aHJ5d2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjIzNTQsImV4cCI6MjA2MTM5ODM1NH0.aQWyd4sla7_lls6ALGjXciTa0JnieySmWYJNTHM0ZEQ"
LOCAL_URL="http://localhost:54321"
LOCAL_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyMjYxNDgyMiwiZXhwIjoxOTM4MTkwODIyfQ.ZDj4ZPXzyQy6LA7WL5RqWzF1NEg-QmP5ABHrGa_LBQI"

# Hàm cập nhật file client.ts
update_client_file() {
    local env=$1
    local target_file="src/integrations/supabase/client.ts"
    
    if [ "$env" = "local" ]; then
        url=$LOCAL_URL
        key=$LOCAL_KEY
        echo "Chuyển sang môi trường Local Supabase..."
    else
        url=$PROD_URL
        key=$PROD_KEY
        echo "Chuyển sang môi trường Production Supabase..."
    fi
    
    # Tạo nội dung file mới
    cat > "$target_file" << EOF
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "${url}";
const SUPABASE_PUBLISHABLE_KEY = "${key}";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
EOF

    echo "Đã cập nhật file $target_file thành công!"
}

# Kiểm tra tham số đầu vào
if [ "$1" = "local" ] || [ "$1" = "prod" ]; then
    update_client_file $1
else
    echo "Sử dụng: $0 [local|prod]"
    echo "  local: Chuyển sang môi trường Local Supabase"
    echo "  prod:  Chuyển sang môi trường Production Supabase"
    exit 1
fi

