
#!/bin/bash

# Định nghĩa các biến môi trường mặc định
PROD_URL="https://eknujhmrispkgzhrywfv.supabase.co"
PROD_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbnVqaG1yaXNwa2d6aHJ5d2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjIzNTQsImV4cCI6MjA2MTM5ODM1NH0.aQWyd4sla7_lls6ALGjXciTa0JnieySmWYJNTHM0ZEQ"
LOCAL_URL="http://localhost:54321"
LOCAL_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyMjYxNDgyMiwiZXhwIjoxOTM4MTkwODIyfQ.ZDj4ZPXzyQy6LA7WL5RqWzF1NEg-QmP5ABHrGa_LBQI"
TEMP_DIR="./temp_schema"
MIGRATION_FILE="./migration_backup.sql"

# Hàm để nhập thông tin schema
get_schema_info() {
    # Nhập tên project/website
    read -p "Nhập tên website/project: " PROJECT_NAME
    
    # Nhập schema name
    read -p "Nhập tên schema: " SCHEMA_NAME
    
    # Nhập username cho schema này
    read -p "Nhập username được phép truy cập schema này: " DB_USER
    
    # Tạo tên file schema dựa trên tên project
    SCHEMA_FILE="$TEMP_DIR/${PROJECT_NAME}_schema.sql"
    
    echo "Thông tin đã nhập:"
    echo "- Website/Project: $PROJECT_NAME"
    echo "- Schema: $SCHEMA_NAME"
    echo "- User: $DB_USER"
    echo "- File schema sẽ được lưu tại: $SCHEMA_FILE"
    
    # Xác nhận thông tin
    read -p "Thông tin trên đã chính xác? (y/n): " CONFIRM
    if [ "$CONFIRM" != "y" ]; then
        echo "Hủy thao tác. Vui lòng thực hiện lại."
        exit 1
    fi
}

# Hàm cập nhật file client.ts
update_client_file() {
    local env=$1
    local target_file="src/integrations/supabase/client.ts"
    
    if [ "$env" = "local" ]; then
        url=$LOCAL_URL
        key=$LOCAL_KEY
        echo "Chuyển sang môi trường Local Supabase..."
    else
        url=$PROD_URL
        key=$PROD_KEY
        echo "Chuyển sang môi trường Production Supabase..."
    fi
    
    # Tạo nội dung file mới với schema được chỉ định
    cat > "$target_file" << EOF
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "${url}";
const SUPABASE_PUBLISHABLE_KEY = "${key}";
const SCHEMA = "${SCHEMA_NAME}";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
    SUPABASE_URL, 
    SUPABASE_PUBLISHABLE_KEY,
    {
        db: {
            schema: SCHEMA
        }
    }
);
EOF

    echo "Đã cập nhật file $target_file thành công với schema $SCHEMA_NAME!"
}

# Kiểm tra Supabase CLI đã được cài đặt chưa
check_supabase_cli() {
    if ! command -v supabase &> /dev/null; then
        echo "Supabase CLI chưa được cài đặt. Vui lòng cài đặt theo các bước sau:"
        echo "1. Cài đặt Supabase CLI:"
        echo "   npm install -g supabase"
        echo "2. Login vào Supabase:"
        echo "   supabase login"
        exit 1
    fi
}

# Backup schema và migration từ production
backup_schema() {
    echo "Đang sao lưu schema $SCHEMA_NAME từ Supabase production..."
    
    # Tạo thư mục tạm nếu chưa tồn tại
    mkdir -p $TEMP_DIR
    
    # Sao lưu schema hiện tại
    echo "Đang sao lưu schema..."
    supabase db dump \
        --db-url "postgresql://postgres:postgres@$PROD_URL:5432/postgres" \
        --schema "$SCHEMA_NAME" \
        -f "$SCHEMA_FILE"
    
    if [ $? -eq 0 ]; then
        echo "Sao lưu schema thành công: $SCHEMA_FILE"
    else
        echo "Sao lưu schema thất bại!"
        exit 1
    fi

    # Sao lưu migration history của schema
    echo "Đang sao lưu migration history cho schema $SCHEMA_NAME..."
    supabase db dump \
        --db-url "postgresql://postgres:postgres@$PROD_URL:5432/postgres" \
        --schema "$SCHEMA_NAME" \
        --migration-table \
        -f "${SCHEMA_FILE}.migration"
    
    if [ $? -eq 0 ]; then
        echo "Sao lưu migration history thành công: ${SCHEMA_FILE}.migration"
    else
        echo "Sao lưu migration history thất bại!"
        exit 1
    fi
}

# Khôi phục schema vào local
restore_schema() {
    echo "Đang khôi phục database schema $SCHEMA_NAME vào Supabase local..."
    
    # Reset schema cụ thể trên database local
    echo "Đang reset schema $SCHEMA_NAME trên database local..."
    supabase db reset \
        --db-url "postgresql://postgres:postgres@localhost:54321/postgres" \
        --schema "$SCHEMA_NAME"
    
    if [ $? -eq 0 ]; then
        echo "Reset schema local thành công"
    else
        echo "Reset schema local thất bại!"
        exit 1
    fi
    
    # Khôi phục schema
    echo "Đang khôi phục schema $SCHEMA_NAME..."
    supabase db push \
        --db-url "postgresql://postgres:postgres@localhost:54321/postgres" \
        --schema "$SCHEMA_NAME" \
        -f "$SCHEMA_FILE"
    
    if [ $? -eq 0 ]; then
        echo "Khôi phục schema thành công"
    else
        echo "Khôi phục schema thất bại!"
        exit 1
    fi
    
    # Khôi phục migration history cho schema
    echo "Đang khôi phục migration history cho schema $SCHEMA_NAME..."
    supabase db push \
        --db-url "postgresql://postgres:postgres@localhost:54321/postgres" \
        --schema "$SCHEMA_NAME" \
        -f "${SCHEMA_FILE}.migration"
    
    if [ $? -eq 0 ]; then
        echo "Khôi phục migration history thành công"
    else
        echo "Khôi phục migration history thất bại!"
        exit 1
    fi

    # Cấp quyền cho user trên schema
    echo "Đang cấp quyền cho user $DB_USER trên schema $SCHEMA_NAME..."
    psql "postgresql://postgres:postgres@localhost:54321/postgres" << EOF
GRANT USAGE ON SCHEMA $SCHEMA_NAME TO $DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $SCHEMA_NAME TO $DB_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $SCHEMA_NAME TO $DB_USER;
EOF
    
    if [ $? -eq 0 ]; then
        echo "Cấp quyền thành công cho user $DB_USER trên schema $SCHEMA_NAME"
    else
        echo "Cấp quyền thất bại!"
        exit 1
    fi
}

# Kiểm tra status của Supabase local
check_local_status() {
    echo "Kiểm tra trạng thái Supabase local..."
    supabase status
    
    if [ $? -ne 0 ]; then
        echo "Supabase local chưa được khởi động. Đang khởi động..."
        supabase start
    fi
}

# Hiển thị hướng dẫn sử dụng
show_usage() {
    echo "Sử dụng: $0 [local|prod|backup|restore|sync]"
    echo "  local:   Chuyển sang môi trường Local Supabase"
    echo "  prod:    Chuyển sang môi trường Production Supabase"
    echo "  backup:  Sao lưu schema và migration từ Supabase Production"
    echo "  restore: Khôi phục schema và migration vào Supabase Local"
    echo "  sync:    Thực hiện toàn bộ quá trình (backup -> restore -> switch to local)"
    exit 1
}

# Xử lý tham số đầu vào
case "$1" in
    "local"|"prod")
        get_schema_info
        update_client_file $1
        ;;
    "backup")
        check_supabase_cli
        get_schema_info
        backup_schema
        ;;
    "restore")
        check_supabase_cli
        check_local_status
        get_schema_info
        restore_schema
        ;;
    "sync")
        check_supabase_cli
        check_local_status
        get_schema_info
        backup_schema
        restore_schema
        update_client_file "local"
        ;;
    *)
        show_usage
        ;;
esac

