
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Kiểm tra môi trường để quyết định sử dụng URL và key nào
const SUPABASE_URL = process.env.NODE_ENV === 'development' 
  ? "http://localhost:54321"
  : "https://eknujhmrispkgzhrywfv.supabase.co";

const SUPABASE_PUBLISHABLE_KEY = process.env.NODE_ENV === 'development'
  ? "your_local_anon_key"
  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbnVqaG1yaXNwa2d6aHJ5d2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjIzNTQsImV4cCI6MjA2MTM5ODM1NH0.aQWyd4sla7_lls6ALGjXciTa0JnieySmWYJNTHM0ZEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
